version: "3.9"
services:
  database_challenge:
    image: postgres
    container_name: database_challenge
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: desafio31
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - database_challenge
    depends_on:
      - database_challenge

volumes:
  pgdata:
    driver: local
